name: "Test MacOS"
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macOS-13 ]
        api: [ 25 ]
        abi: [ x86 ]
        java_version: [ 17 ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java_version }}
      - name: install node
        run: |
          brew install node
          brew install nvm
          mkdir ~/.nvm
          export NVM_DIR="$HOME/.nvm"
          [ -s "/usr/local/opt/nvm/nvm.sh" ] && \. "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
          [ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
      - name: test install-sdk
        run: npm config delete prefix && source ~/.nvm/nvm.sh && nvm install v20.12.1 && npm install && npm ci && npm run build
        working-directory: install-sdk
      - name: test emulator-run-cmd
        run: npm config delete prefix && source ~/.nvm/nvm.sh && nvm install v20.12.1 && npm install && npm ci && npm run build
        working-directory: emulator-run-cmd
      - uses: ./install-sdk
        name: install sdk
      - run: sdkmanager platform-tools
      - run: adb devices
      - uses: ./emulator-run-cmd
        with:
          api: ${{ matrix.api }}
          tag: default
          abi: ${{ matrix.abi }}
          cmd: adb shell getprop
          bootTimeout: 500
          portNumber: 5555
      - uses: actions/upload-artifact@v4
        with:
          name: logcat-${{ matrix.os }}-${{ matrix.api }}
          path: artifacts/logcat.log
