name: "Test MacOS"
on:
  push:
    branches:
      - master
  pull_request:
jobs:
#  test-ubuntu-latest:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v4
#    - name: Set up JDK 17
#      uses: actions/setup-java@v4
#      with:
#        distribution: 'temurin'
#        java-version: '17'
#    - name: test install-sdk
#      run: npm config delete prefix && source ~/.nvm/nvm.sh && nvm install v16.15.0 && npm install && npm ci && npm run build
#      working-directory: install-sdk
#    - name: test emulator-run-cmd
#      run: npm config delete prefix && source ~/.nvm/nvm.sh && nvm install v16.15.0 && npm install && npm ci && npm run build
#      working-directory: emulator-run-cmd
#    - uses: ./install-sdk
#      name: install sdk
#    - run: sdkmanager platform-tools
#    - run: adb devices
#    - name: Enable KVM
#      run: |
#        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
#        sudo udevadm control --reload-rules
#        sudo udevadm trigger --name-match=kvm
#    - uses: ./emulator-run-cmd
#      with:
#        api: 25
#        tag: default
#        abi: x86
#        cmd: adb shell getprop
#        bootTimeout: 500
#    - uses: actions/upload-artifact@v4
#      with:
#        name: logcat
#        path: artifacts/logcat.log
  test-macos-13:
    runs-on: macOS-13
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: install node
        run: |
          brew install node
          brew install nvm
          mkdir ~/.nvm
          export NVM_DIR="$HOME/.nvm"
          [ -s "/usr/local/opt/nvm/nvm.sh" ] && \. "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
          [ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
      - name: test install-sdk
        run: npm config delete prefix && source ~/.nvm/nvm.sh && nvm install v20.12.1 && npm install && npm ci && npm run build
        working-directory: install-sdk
      - name: test emulator-run-cmd
        run: npm config delete prefix && source ~/.nvm/nvm.sh && nvm install v20.12.1 && npm install && npm ci && npm run build
        working-directory: emulator-run-cmd
      - uses: ./install-sdk
        name: install sdk
      - run: sdkmanager platform-tools
      - run: adb devices
      - uses: ./emulator-run-cmd
        with:
          api: 25
          tag: default
          abi: x86
          cmd: adb shell getprop
          bootTimeout: 500
      - uses: actions/upload-artifact@v4
        with:
          name: logcat
          path: artifacts/logcat.log
